# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diskimagewidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiskImageWidget(object):
    def setupUi(self, DiskImageWidget):
        DiskImageWidget.setObjectName("DiskImageWidget")
        DiskImageWidget.resize(1221, 608)
        self.toHostPushButton = QtWidgets.QPushButton(DiskImageWidget)
        self.toHostPushButton.setGeometry(QtCore.QRect(540, 330, 141, 41))
        self.toHostPushButton.setText("")
        self.toHostPushButton.setObjectName("toHostPushButton")
        self.toGuestPushButton = QtWidgets.QPushButton(DiskImageWidget)
        self.toGuestPushButton.setGeometry(QtCore.QRect(540, 280, 141, 41))
        self.toGuestPushButton.setText("")
        self.toGuestPushButton.setObjectName("toGuestPushButton")
        self.frame = QtWidgets.QFrame(DiskImageWidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 521, 591))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hostTreeView = QtWidgets.QTreeView(self.frame)
        self.hostTreeView.setGeometry(QtCore.QRect(10, 80, 500, 500))
        self.hostTreeView.setObjectName("hostTreeView")
        self.hostComboBox = QtWidgets.QComboBox(self.frame)
        self.hostComboBox.setGeometry(QtCore.QRect(10, 40, 500, 31))
        self.hostComboBox.setObjectName("hostComboBox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 10, 67, 17))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(DiskImageWidget)
        self.frame_2.setGeometry(QtCore.QRect(690, 10, 521, 591))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.guestTreeView = QtWidgets.QTreeView(self.frame_2)
        self.guestTreeView.setGeometry(QtCore.QRect(10, 80, 500, 500))
        self.guestTreeView.setObjectName("guestTreeView")
        self.guestComboBox = QtWidgets.QComboBox(self.frame_2)
        self.guestComboBox.setGeometry(QtCore.QRect(10, 40, 500, 31))
        self.guestComboBox.setObjectName("guestComboBox")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 67, 17))
        self.label_2.setObjectName("label_2")
        self.detailsPushButton = QtWidgets.QPushButton(DiskImageWidget)
        self.detailsPushButton.setGeometry(QtCore.QRect(540, 400, 141, 41))
        self.detailsPushButton.setObjectName("detailsPushButton")
        self.frame_2.raise_()
        self.frame.raise_()
        self.toHostPushButton.raise_()
        self.toGuestPushButton.raise_()
        self.detailsPushButton.raise_()

        self.retranslateUi(DiskImageWidget)
        QtCore.QMetaObject.connectSlotsByName(DiskImageWidget)

    def retranslateUi(self, DiskImageWidget):
        _translate = QtCore.QCoreApplication.translate
        DiskImageWidget.setWindowTitle(_translate("DiskImageWidget", "Modify Guest Image"))
        self.label.setText(_translate("DiskImageWidget", "Host"))
        self.label_2.setText(_translate("DiskImageWidget", "Guest"))
        self.detailsPushButton.setText(_translate("DiskImageWidget", "Show Details"))
