# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 508)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.ghLogoLabel = QtWidgets.QLabel(self.widget)
        self.ghLogoLabel.setGeometry(QtCore.QRect(560, 350, 100, 100))
        self.ghLogoLabel.setText("")
        self.ghLogoLabel.setObjectName("ghLogoLabel")
        self.jstarLogoLabel = QtWidgets.QLabel(self.widget)
        self.jstarLogoLabel.setGeometry(QtCore.QRect(690, 340, 220, 100))
        self.jstarLogoLabel.setText("")
        self.jstarLogoLabel.setObjectName("jstarLogoLabel")
        self.terminalTabWidget = QtWidgets.QTabWidget(self.widget)
        self.terminalTabWidget.setGeometry(QtCore.QRect(20, 10, 531, 441))
        self.terminalTabWidget.setObjectName("terminalTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.terminalTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.terminalTabWidget.addTab(self.tab_2, "")
        self.qemuInstanceTable = QtWidgets.QTableView(self.widget)
        self.qemuInstanceTable.setGeometry(QtCore.QRect(560, 10, 581, 291))
        self.qemuInstanceTable.setObjectName("qemuInstanceTable")
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1150, 22))
        self.menubar.setObjectName("menubar")
        self.menuAFRL_RWWN_QEMU_Launcher = QtWidgets.QMenu(self.menubar)
        self.menuAFRL_RWWN_QEMU_Launcher.setObjectName("menuAFRL_RWWN_QEMU_Launcher")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_file_new_qemu_instance = QtWidgets.QAction(MainWindow)
        self.action_file_new_qemu_instance.setObjectName("action_file_new_qemu_instance")
        self.action_help_about = QtWidgets.QAction(MainWindow)
        self.action_help_about.setObjectName("action_help_about")
        self.action_file_exit = QtWidgets.QAction(MainWindow)
        self.action_file_exit.setObjectName("action_file_exit")
        self.actionModify_Image_Contents = QtWidgets.QAction(MainWindow)
        self.actionModify_Image_Contents.setObjectName("actionModify_Image_Contents")
        self.menuAFRL_RWWN_QEMU_Launcher.addAction(self.action_file_new_qemu_instance)
        self.menuAFRL_RWWN_QEMU_Launcher.addSeparator()
        self.menuAFRL_RWWN_QEMU_Launcher.addAction(self.actionModify_Image_Contents)
        self.menuAFRL_RWWN_QEMU_Launcher.addAction(self.action_file_exit)
        self.menuHelp.addAction(self.action_help_about)
        self.menubar.addAction(self.menuAFRL_RWWN_QEMU_Launcher.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.terminalTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.terminalTabWidget.setTabText(self.terminalTabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.terminalTabWidget.setTabText(self.terminalTabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuAFRL_RWWN_QEMU_Launcher.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.action_file_new_qemu_instance.setText(_translate("MainWindow", "New QEMU Instance"))
        self.action_file_new_qemu_instance.setToolTip(_translate("MainWindow", "Opens wizard to create a new QEMU instance"))
        self.action_help_about.setText(_translate("MainWindow", "About"))
        self.action_file_exit.setText(_translate("MainWindow", "Exit"))
        self.actionModify_Image_Contents.setText(_translate("MainWindow", "Modify Image Contents"))
        self.actionModify_Image_Contents.setToolTip(_translate("MainWindow", "Opens GUI to copy items into guest image"))
