# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qemulaunchwizard.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QListView, QPlainTextEdit, QPushButton,
    QSizePolicy, QWidget, QWizard, QWizardPage)

class Ui_qemuLaunchWizard(object):
    def setupUi(self, qemuLaunchWizard):
        if not qemuLaunchWizard.objectName():
            qemuLaunchWizard.setObjectName(u"qemuLaunchWizard")
        qemuLaunchWizard.resize(397, 415)
        self.qemuLaunchWizardNamePage = QWizardPage()
        self.qemuLaunchWizardNamePage.setObjectName(u"qemuLaunchWizardNamePage")
        self.nameLineEdit = QLineEdit(self.qemuLaunchWizardNamePage)
        self.nameLineEdit.setObjectName(u"nameLineEdit")
        self.nameLineEdit.setGeometry(QRect(130, 50, 221, 30))
        self.nameLabel = QLabel(self.qemuLaunchWizardNamePage)
        self.nameLabel.setObjectName(u"nameLabel")
        self.nameLabel.setGeometry(QRect(50, 50, 70, 30))
        self.nameLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.descritionLabel = QLabel(self.qemuLaunchWizardNamePage)
        self.descritionLabel.setObjectName(u"descritionLabel")
        self.descritionLabel.setGeometry(QRect(29, 100, 91, 30))
        self.descritionLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.descriptionPlainTextEdit = QPlainTextEdit(self.qemuLaunchWizardNamePage)
        self.descriptionPlainTextEdit.setObjectName(u"descriptionPlainTextEdit")
        self.descriptionPlainTextEdit.setGeometry(QRect(130, 110, 221, 131))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardNamePage)
        self.qemuLaunchWizardImagePage = QWizardPage()
        self.qemuLaunchWizardImagePage.setObjectName(u"qemuLaunchWizardImagePage")
        self.frame_6 = QFrame(self.qemuLaunchWizardImagePage)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 100, 361, 101))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.imageSelectButton = QPushButton(self.frame_6)
        self.imageSelectButton.setObjectName(u"imageSelectButton")
        self.imageSelectButton.setGeometry(QRect(320, 10, 30, 30))
        icon = QIcon()
        icon.addFile(u"../resources/document-open.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u"../resources/document-open.png", QSize(), QIcon.Normal, QIcon.On)
        self.imageSelectButton.setIcon(icon)
        self.imageLineEdit = QLineEdit(self.frame_6)
        self.imageLineEdit.setObjectName(u"imageLineEdit")
        self.imageLineEdit.setGeometry(QRect(150, 10, 171, 30))
        self.imageLabel = QLabel(self.frame_6)
        self.imageLabel.setObjectName(u"imageLabel")
        self.imageLabel.setGeometry(QRect(10, 10, 111, 30))
        self.modImagePushButton = QPushButton(self.frame_6)
        self.modImagePushButton.setObjectName(u"modImagePushButton")
        self.modImagePushButton.setGeometry(QRect(178, 50, 171, 31))
        self.frame_8 = QFrame(self.qemuLaunchWizardImagePage)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 0, 361, 91))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.configLineEdit = QLineEdit(self.frame_8)
        self.configLineEdit.setObjectName(u"configLineEdit")
        self.configLineEdit.setGeometry(QRect(150, 20, 171, 30))
        self.configSelectButton = QPushButton(self.frame_8)
        self.configSelectButton.setObjectName(u"configSelectButton")
        self.configSelectButton.setGeometry(QRect(320, 20, 30, 30))
        self.configSelectButton.setIcon(icon)
        self.configLabel = QLabel(self.frame_8)
        self.configLabel.setObjectName(u"configLabel")
        self.configLabel.setGeometry(QRect(10, 20, 141, 30))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardImagePage)
        self.qemuLaunchWizardNetworkPage = QWizardPage()
        self.qemuLaunchWizardNetworkPage.setObjectName(u"qemuLaunchWizardNetworkPage")
        self.frame_7 = QFrame(self.qemuLaunchWizardNetworkPage)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(0, 0, 361, 231))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.ipLineEdit = QLineEdit(self.frame_7)
        self.ipLineEdit.setObjectName(u"ipLineEdit")
        self.ipLineEdit.setGeometry(QRect(150, 60, 171, 30))
        self.gatewayLabel = QLabel(self.frame_7)
        self.gatewayLabel.setObjectName(u"gatewayLabel")
        self.gatewayLabel.setGeometry(QRect(30, 100, 111, 30))
        self.ipLabel = QLabel(self.frame_7)
        self.ipLabel.setObjectName(u"ipLabel")
        self.ipLabel.setGeometry(QRect(30, 60, 111, 30))
        self.subnetMaskLabel = QLabel(self.frame_7)
        self.subnetMaskLabel.setObjectName(u"subnetMaskLabel")
        self.subnetMaskLabel.setGeometry(QRect(30, 140, 111, 30))
        self.gatewayLineEdit = QLineEdit(self.frame_7)
        self.gatewayLineEdit.setObjectName(u"gatewayLineEdit")
        self.gatewayLineEdit.setGeometry(QRect(150, 100, 171, 30))
        self.subnetMaskLineEdit = QLineEdit(self.frame_7)
        self.subnetMaskLineEdit.setObjectName(u"subnetMaskLineEdit")
        self.subnetMaskLineEdit.setGeometry(QRect(150, 140, 171, 30))
        self.ifaceLabel = QLabel(self.frame_7)
        self.ifaceLabel.setObjectName(u"ifaceLabel")
        self.ifaceLabel.setGeometry(QRect(30, 20, 111, 30))
        self.ifaceLineEdit = QLineEdit(self.frame_7)
        self.ifaceLineEdit.setObjectName(u"ifaceLineEdit")
        self.ifaceLineEdit.setGeometry(QRect(150, 20, 171, 30))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardNetworkPage)
        self.qemuLaunchWizardDevicePage = QWizardPage()
        self.qemuLaunchWizardDevicePage.setObjectName(u"qemuLaunchWizardDevicePage")
        self.frame_3 = QFrame(self.qemuLaunchWizardDevicePage)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 0, 371, 101))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.deviceTypeLabel = QLabel(self.frame_3)
        self.deviceTypeLabel.setObjectName(u"deviceTypeLabel")
        self.deviceTypeLabel.setGeometry(QRect(8, 10, 81, 31))
        self.deviceTypeLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.deviceLabel = QLabel(self.frame_3)
        self.deviceLabel.setObjectName(u"deviceLabel")
        self.deviceLabel.setGeometry(QRect(38, 50, 51, 31))
        self.deviceLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.deviceTypeComboBox = QComboBox(self.frame_3)
        self.deviceTypeComboBox.setObjectName(u"deviceTypeComboBox")
        self.deviceTypeComboBox.setGeometry(QRect(100, 10, 191, 31))
        self.deviceComboBox = QComboBox(self.frame_3)
        self.deviceComboBox.setObjectName(u"deviceComboBox")
        self.deviceComboBox.setGeometry(QRect(100, 50, 191, 31))
        self.addDevicePushButton = QPushButton(self.frame_3)
        self.addDevicePushButton.setObjectName(u"addDevicePushButton")
        self.addDevicePushButton.setGeometry(QRect(300, 10, 61, 71))
        self.frame_4 = QFrame(self.qemuLaunchWizardDevicePage)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(0, 110, 371, 241))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.deviceListView = QListView(self.frame_4)
        self.deviceListView.setObjectName(u"deviceListView")
        self.deviceListView.setGeometry(QRect(0, 0, 291, 231))
        self.removeDevicePushButton = QPushButton(self.frame_4)
        self.removeDevicePushButton.setObjectName(u"removeDevicePushButton")
        self.removeDevicePushButton.setGeometry(QRect(300, 80, 61, 61))
        self.editDevicePushButton = QPushButton(self.frame_4)
        self.editDevicePushButton.setObjectName(u"editDevicePushButton")
        self.editDevicePushButton.setGeometry(QRect(300, 10, 61, 61))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardDevicePage)

        self.retranslateUi(qemuLaunchWizard)

        QMetaObject.connectSlotsByName(qemuLaunchWizard)
    # setupUi

    def retranslateUi(self, qemuLaunchWizard):
        qemuLaunchWizard.setWindowTitle(QCoreApplication.translate("qemuLaunchWizard", u"QEMU Configuration Wizard", None))
        self.nameLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Name", None))
        self.descritionLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Description", None))
        self.imageSelectButton.setText("")
        self.imageLineEdit.setText("")
        self.imageLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Image File", None))
        self.modImagePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Modify Image Contents", None))
        self.configLineEdit.setText("")
        self.configSelectButton.setText("")
        self.configLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Config File", None))
        self.qemuLaunchWizardNetworkPage.setTitle("")
        self.ipLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"000.000.000.000", None))
        self.gatewayLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Gateway", None))
        self.ipLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"IP Address", None))
        self.subnetMaskLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Subnet Mask", None))
        self.gatewayLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"000.000.000.000", None))
        self.subnetMaskLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"000.000.000.000", None))
        self.ifaceLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Interface Name", None))
        self.ifaceLineEdit.setText("")
        self.deviceTypeLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Device Type", None))
        self.deviceLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Device", None))
        self.addDevicePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Add", None))
        self.removeDevicePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Remove", None))
        self.editDevicePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Edit", None))
    # retranslateUi

