# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qemulaunchwizard.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QListView, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpinBox, QWidget,
    QWizard, QWizardPage)

class Ui_qemuLaunchWizard(object):
    def setupUi(self, qemuLaunchWizard):
        if not qemuLaunchWizard.objectName():
            qemuLaunchWizard.setObjectName(u"qemuLaunchWizard")
        qemuLaunchWizard.resize(397, 415)
        self.qemuLaunchWizardNamePage = QWizardPage()
        self.qemuLaunchWizardNamePage.setObjectName(u"qemuLaunchWizardNamePage")
        self.nameLineEdit = QLineEdit(self.qemuLaunchWizardNamePage)
        self.nameLineEdit.setObjectName(u"nameLineEdit")
        self.nameLineEdit.setGeometry(QRect(130, 50, 221, 30))
        self.nameLabel = QLabel(self.qemuLaunchWizardNamePage)
        self.nameLabel.setObjectName(u"nameLabel")
        self.nameLabel.setGeometry(QRect(50, 50, 70, 30))
        self.nameLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.descritionLabel = QLabel(self.qemuLaunchWizardNamePage)
        self.descritionLabel.setObjectName(u"descritionLabel")
        self.descritionLabel.setGeometry(QRect(29, 100, 91, 30))
        self.descritionLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.descriptionPlainTextEdit = QPlainTextEdit(self.qemuLaunchWizardNamePage)
        self.descriptionPlainTextEdit.setObjectName(u"descriptionPlainTextEdit")
        self.descriptionPlainTextEdit.setGeometry(QRect(130, 110, 221, 131))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardNamePage)
        self.qemuLaunchWizardMachineCpuPage = QWizardPage()
        self.qemuLaunchWizardMachineCpuPage.setObjectName(u"qemuLaunchWizardMachineCpuPage")
        self.frame = QFrame(self.qemuLaunchWizardMachineCpuPage)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 0, 361, 101))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.boardSettings_PushButton = QPushButton(self.frame)
        self.boardSettings_PushButton.setObjectName(u"boardSettings_PushButton")
        self.boardSettings_PushButton.setGeometry(QRect(170, 60, 151, 31))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(42, 20, 81, 31))
        self.machineComboBox = QComboBox(self.frame)
        self.machineComboBox.setObjectName(u"machineComboBox")
        self.machineComboBox.setGeometry(QRect(130, 20, 191, 31))
        self.frame_2 = QFrame(self.qemuLaunchWizardMachineCpuPage)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 110, 361, 151))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 10, 81, 31))
        self.cpuComboBox = QComboBox(self.frame_2)
        self.cpuComboBox.setObjectName(u"cpuComboBox")
        self.cpuComboBox.setGeometry(QRect(130, 10, 191, 31))
        self.cpuSettings_PushButton = QPushButton(self.frame_2)
        self.cpuSettings_PushButton.setObjectName(u"cpuSettings_PushButton")
        self.cpuSettings_PushButton.setGeometry(QRect(170, 110, 151, 31))
        self.smpLabel = QLabel(self.frame_2)
        self.smpLabel.setObjectName(u"smpLabel")
        self.smpLabel.setGeometry(QRect(40, 60, 81, 31))
        self.smpLineEdit = QLineEdit(self.frame_2)
        self.smpLineEdit.setObjectName(u"smpLineEdit")
        self.smpLineEdit.setGeometry(QRect(130, 60, 113, 31))
        self.smpAllCheckBox = QCheckBox(self.frame_2)
        self.smpAllCheckBox.setObjectName(u"smpAllCheckBox")
        self.smpAllCheckBox.setGeometry(QRect(270, 60, 51, 31))
        self.frame_5 = QFrame(self.qemuLaunchWizardMachineCpuPage)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 270, 361, 80))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.memoryLabel = QLabel(self.frame_5)
        self.memoryLabel.setObjectName(u"memoryLabel")
        self.memoryLabel.setGeometry(QRect(40, 30, 81, 31))
        self.memorySpinBox = QSpinBox(self.frame_5)
        self.memorySpinBox.setObjectName(u"memorySpinBox")
        self.memorySpinBox.setGeometry(QRect(130, 30, 201, 31))
        self.memorySpinBox.setSuffix(u"MB")
        self.memorySpinBox.setMinimum(4)
        self.memorySpinBox.setMaximum(16384)
        self.memorySpinBox.setValue(128)
        qemuLaunchWizard.addPage(self.qemuLaunchWizardMachineCpuPage)
        self.qemuLaunchWizardDevicePage = QWizardPage()
        self.qemuLaunchWizardDevicePage.setObjectName(u"qemuLaunchWizardDevicePage")
        self.frame_3 = QFrame(self.qemuLaunchWizardDevicePage)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 0, 371, 101))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.deviceTypeLabel = QLabel(self.frame_3)
        self.deviceTypeLabel.setObjectName(u"deviceTypeLabel")
        self.deviceTypeLabel.setGeometry(QRect(8, 10, 81, 31))
        self.deviceTypeLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.deviceLabel = QLabel(self.frame_3)
        self.deviceLabel.setObjectName(u"deviceLabel")
        self.deviceLabel.setGeometry(QRect(38, 50, 51, 31))
        self.deviceLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.deviceTypeComboBox = QComboBox(self.frame_3)
        self.deviceTypeComboBox.setObjectName(u"deviceTypeComboBox")
        self.deviceTypeComboBox.setGeometry(QRect(100, 10, 191, 31))
        self.deviceComboBox = QComboBox(self.frame_3)
        self.deviceComboBox.setObjectName(u"deviceComboBox")
        self.deviceComboBox.setGeometry(QRect(100, 50, 191, 31))
        self.addDevicePushButton = QPushButton(self.frame_3)
        self.addDevicePushButton.setObjectName(u"addDevicePushButton")
        self.addDevicePushButton.setGeometry(QRect(300, 10, 61, 71))
        self.frame_4 = QFrame(self.qemuLaunchWizardDevicePage)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(0, 110, 371, 241))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.deviceListView = QListView(self.frame_4)
        self.deviceListView.setObjectName(u"deviceListView")
        self.deviceListView.setGeometry(QRect(0, 0, 291, 231))
        self.removeDevicePushButton = QPushButton(self.frame_4)
        self.removeDevicePushButton.setObjectName(u"removeDevicePushButton")
        self.removeDevicePushButton.setGeometry(QRect(300, 80, 61, 61))
        self.editDevicePushButton = QPushButton(self.frame_4)
        self.editDevicePushButton.setObjectName(u"editDevicePushButton")
        self.editDevicePushButton.setGeometry(QRect(300, 10, 61, 61))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardDevicePage)
        self.qemuLaunchWizardImagePage = QWizardPage()
        self.qemuLaunchWizardImagePage.setObjectName(u"qemuLaunchWizardImagePage")
        self.frame_6 = QFrame(self.qemuLaunchWizardImagePage)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 10, 361, 141))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.imageSelectButton = QPushButton(self.frame_6)
        self.imageSelectButton.setObjectName(u"imageSelectButton")
        self.imageSelectButton.setGeometry(QRect(320, 10, 30, 30))
        icon = QIcon()
        icon.addFile(u"../resources/document-open.png", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u"../resources/document-open.png", QSize(), QIcon.Normal, QIcon.On)
        self.imageSelectButton.setIcon(icon)
        self.imageLineEdit = QLineEdit(self.frame_6)
        self.imageLineEdit.setObjectName(u"imageLineEdit")
        self.imageLineEdit.setGeometry(QRect(150, 10, 171, 30))
        self.imageLabel = QLabel(self.frame_6)
        self.imageLabel.setObjectName(u"imageLabel")
        self.imageLabel.setGeometry(QRect(10, 10, 111, 30))
        self.modImagePushButton = QPushButton(self.frame_6)
        self.modImagePushButton.setObjectName(u"modImagePushButton")
        self.modImagePushButton.setGeometry(QRect(178, 50, 171, 31))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardImagePage)
        self.qemuLaunchWizardNetworkPage = QWizardPage()
        self.qemuLaunchWizardNetworkPage.setObjectName(u"qemuLaunchWizardNetworkPage")
        self.frame_7 = QFrame(self.qemuLaunchWizardNetworkPage)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(0, 0, 361, 231))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.ipLineEdit = QLineEdit(self.frame_7)
        self.ipLineEdit.setObjectName(u"ipLineEdit")
        self.ipLineEdit.setGeometry(QRect(150, 60, 171, 30))
        self.gatewayLabel = QLabel(self.frame_7)
        self.gatewayLabel.setObjectName(u"gatewayLabel")
        self.gatewayLabel.setGeometry(QRect(30, 100, 111, 30))
        self.ipLabel = QLabel(self.frame_7)
        self.ipLabel.setObjectName(u"ipLabel")
        self.ipLabel.setGeometry(QRect(30, 60, 111, 30))
        self.subnetMaskLabel = QLabel(self.frame_7)
        self.subnetMaskLabel.setObjectName(u"subnetMaskLabel")
        self.subnetMaskLabel.setGeometry(QRect(30, 140, 111, 30))
        self.gatewayLineEdit = QLineEdit(self.frame_7)
        self.gatewayLineEdit.setObjectName(u"gatewayLineEdit")
        self.gatewayLineEdit.setGeometry(QRect(150, 100, 171, 30))
        self.subnetMaskLineEdit = QLineEdit(self.frame_7)
        self.subnetMaskLineEdit.setObjectName(u"subnetMaskLineEdit")
        self.subnetMaskLineEdit.setGeometry(QRect(150, 140, 171, 30))
        self.ifaceLabel = QLabel(self.frame_7)
        self.ifaceLabel.setObjectName(u"ifaceLabel")
        self.ifaceLabel.setGeometry(QRect(30, 20, 111, 30))
        self.ifaceLineEdit = QLineEdit(self.frame_7)
        self.ifaceLineEdit.setObjectName(u"ifaceLineEdit")
        self.ifaceLineEdit.setGeometry(QRect(150, 20, 171, 30))
        qemuLaunchWizard.addPage(self.qemuLaunchWizardNetworkPage)
        self.qemuLaunchWizardKernelAppPage = QWizardPage()
        self.qemuLaunchWizardKernelAppPage.setObjectName(u"qemuLaunchWizardKernelAppPage")
        self.appButton = QPushButton(self.qemuLaunchWizardKernelAppPage)
        self.appButton.setObjectName(u"appButton")
        self.appButton.setGeometry(QRect(310, 60, 30, 30))
        self.appButton.setIcon(icon)
        self.appLineEdit = QLineEdit(self.qemuLaunchWizardKernelAppPage)
        self.appLineEdit.setObjectName(u"appLineEdit")
        self.appLineEdit.setGeometry(QRect(141, 60, 171, 30))
        self.kernelLineEdit = QLineEdit(self.qemuLaunchWizardKernelAppPage)
        self.kernelLineEdit.setObjectName(u"kernelLineEdit")
        self.kernelLineEdit.setGeometry(QRect(140, 20, 171, 30))
        self.kernelLabel = QLabel(self.qemuLaunchWizardKernelAppPage)
        self.kernelLabel.setObjectName(u"kernelLabel")
        self.kernelLabel.setGeometry(QRect(19, 20, 111, 30))
        self.appLabel = QLabel(self.qemuLaunchWizardKernelAppPage)
        self.appLabel.setObjectName(u"appLabel")
        self.appLabel.setGeometry(QRect(20, 60, 111, 30))
        self.kernelButton = QPushButton(self.qemuLaunchWizardKernelAppPage)
        self.kernelButton.setObjectName(u"kernelButton")
        self.kernelButton.setGeometry(QRect(310, 20, 30, 30))
        self.kernelButton.setIcon(icon)
        qemuLaunchWizard.addPage(self.qemuLaunchWizardKernelAppPage)

        self.retranslateUi(qemuLaunchWizard)

        QMetaObject.connectSlotsByName(qemuLaunchWizard)
    # setupUi

    def retranslateUi(self, qemuLaunchWizard):
        qemuLaunchWizard.setWindowTitle(QCoreApplication.translate("qemuLaunchWizard", u"QEMU Configuration Wizard", None))
        self.nameLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Name", None))
        self.descritionLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Description", None))
        self.qemuLaunchWizardMachineCpuPage.setTitle("")
        self.boardSettings_PushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Advanced Settings", None))
        self.label.setText(QCoreApplication.translate("qemuLaunchWizard", u"Board", None))
        self.label_2.setText(QCoreApplication.translate("qemuLaunchWizard", u"CPU", None))
        self.cpuSettings_PushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Advanced Settings", None))
        self.smpLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"SMP Cores", None))
        self.smpAllCheckBox.setText(QCoreApplication.translate("qemuLaunchWizard", u"ALL", None))
        self.memoryLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Memory", None))
        self.deviceTypeLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Device Type", None))
        self.deviceLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Device", None))
        self.addDevicePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Add", None))
        self.removeDevicePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Remove", None))
        self.editDevicePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Edit", None))
        self.imageSelectButton.setText("")
        self.imageLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"image", None))
        self.imageLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Image File", None))
        self.modImagePushButton.setText(QCoreApplication.translate("qemuLaunchWizard", u"Modify Image Contents", None))
        self.qemuLaunchWizardNetworkPage.setTitle("")
        self.ipLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"000.000.000.000", None))
        self.gatewayLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Gateway", None))
        self.ipLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"IP Address", None))
        self.subnetMaskLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Subnet Mask", None))
        self.gatewayLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"000.000.000.000", None))
        self.subnetMaskLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"000.000.000.000", None))
        self.ifaceLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Interface Name", None))
        self.ifaceLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"eth0", None))
        self.appButton.setText("")
        self.appLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"application", None))
        self.kernelLineEdit.setText(QCoreApplication.translate("qemuLaunchWizard", u"kernel", None))
        self.kernelLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Kernel", None))
        self.appLabel.setText(QCoreApplication.translate("qemuLaunchWizard", u"Application", None))
        self.kernelButton.setText("")
    # retranslateUi

